# Modified for the itcmoe reference-calibration workflow.
# Upstream attribution and license texts: THIRD_PARTY_NOTICES.md and licenses/.
# This file is modified based on https://github.com/huggingface/transformers/blob/v4.52.4/src/transformers/models/qwen3_moe/modeling_qwen3_moe.py.
#
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/qwen3_moe/modular_qwen3_moe.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_qwen3_moe.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# coding=utf-8
# Copyright 2025 The Qwen team, Alibaba Group and the HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from functools import partial
from typing import Callable, List, Optional, Tuple, Union

import torch
import torch.nn.functional as F
from torch import nn

from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache, SlidingWindowCache, StaticCache
from transformers.generation import GenerationMixin
from transformers.integrations import use_kernel_forward_from_hub
from transformers.modeling_attn_mask_utils import AttentionMaskConverter
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_outputs import (
    BaseModelOutputWithPast,
    MoeCausalLMOutputWithPast,
    MoeModelOutputWithPast,
    QuestionAnsweringModelOutput,
    SequenceClassifierOutputWithPast,
    TokenClassifierOutput,
)
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import LossKwargs, auto_docstring, can_return_tuple, is_torch_flex_attn_available, logging

from .configuration_sdar_moe import SDARMoeConfig

# ITCMOE_RUNTIME_PROFILE: runtime counters
try:
    from opencompass.models.team_runtime_profile import (
        add_activated_experts as itcmoe_profile_add_activated_experts,
        add_forward as itcmoe_profile_add_forward,
    )
except Exception:  # profiler unavailable (standalone inference); degrade to no-op
    def itcmoe_profile_add_activated_experts(*_args, **_kwargs):
        return None

    def itcmoe_profile_add_forward(*_args, **_kwargs):
        return None


from flash_attn.ops.triton.layer_norm import rms_norm_fn as flash_rms_norm
try:
    from liger_kernel.ops.swiglu import LigerSiLUMulFunction  # noqa: F401
    liger_kernel_is_available = True
except ImportError:
    liger_kernel_is_available = False

try:
    import triton
    import triton.language as tl
    _sdar_tucker_triton_available = True
except Exception:
    triton = None
    tl = None
    _sdar_tucker_triton_available = False

if is_torch_flex_attn_available():
    from torch.nn.attention.flex_attention import BlockMask

    from transformers.integrations.flex_attention import make_flex_block_causal_mask


logger = logging.get_logger(__name__)


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2:]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`, *optional*):
            Deprecated and unused.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(
        batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs,
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    attn_weights = nn.functional.softmax(
        attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(
        attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


class SDARMoeAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: SDARMoeConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(
            config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        self.q_proj = nn.Linear(
            config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.attention_bias
        )
        self.k_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.v_proj = nn.Linear(
            config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.attention_bias
        )
        self.o_proj = nn.Linear(
            config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.attention_bias
        )
        # unlike olmo, only on the head dim!
        self.q_norm = SDARMoeRMSNorm(self.head_dim, eps=config.rms_norm_eps)
        # thus post q_norm does not need reshape
        self.k_norm = SDARMoeRMSNorm(self.head_dim, eps=config.rms_norm_eps)
        self.sliding_window = config.sliding_window
        if not (
            self.config.use_sliding_window
            and getattr(self.config, "sliding_window", None) is not None
            and self.layer_idx >= self.config.max_window_layers
        ):
            self.sliding_window = None

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: Tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_value: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Tuple[torch.Tensor, Optional[torch.Tensor], Optional[Tuple[torch.Tensor]]]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_norm(self.q_proj(
            hidden_states).view(hidden_shape)).transpose(1, 2)
        key_states = self.k_norm(self.k_proj(
            hidden_states).view(hidden_shape)).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(
            hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(
            query_states, key_states, cos, sin)

        if past_key_value is not None and kwargs.get("store_kv", False):
            # sin and cos are specific to RoPE models; cache_position needed for the static cache
            key_states, value_states = past_key_value.update(
                key_states, value_states, self.layer_idx)
        elif past_key_value is not None and not kwargs.get("store_kv", False) and len(past_key_value) > self.layer_idx:
            # only retrive, do not store kv
            past_key_states, past_value_states = past_key_value[self.layer_idx]
            key_states = torch.cat(
                [past_key_states, key_states], dim=-2
            )
            value_states = torch.cat(
                [past_value_states, value_states], dim=-2
            )
        
        attention_mask = attention_mask.bool() if attention_mask is not None else None
        if torch.all(attention_mask):  # decoding
            attn_output = F.scaled_dot_product_attention(
                query=query_states,
                key=key_states,
                value=value_states,
                attn_mask=attention_mask,
                is_causal=False,
                scale=self.scaling,
                enable_gqa=True)
            attn_output = attn_output.transpose(1, 2).contiguous()

        else:  # prefilling
            attn_output = F.scaled_dot_product_attention(
                query=query_states,
                key=key_states,
                value=value_states,
                attn_mask=attention_mask,
                is_causal=False,
                scale=self.scaling,
                enable_gqa=True)
            attn_output = attn_output.transpose(1, 2).contiguous()

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, None #, attn_weights


class SDARMoeMLP(nn.Module):
    def __init__(self, config, intermediate_size=None):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = intermediate_size if intermediate_size is not None else config.intermediate_size
        self.gate_proj = nn.Linear(
            self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(
            self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(
            self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        if liger_kernel_is_available:
            return self.down_proj(LigerSiLUMulFunction.apply(self.gate_proj(x), self.up_proj(x)))
        else:
            down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
            return down_proj


if _sdar_tucker_triton_available:
    @triton.jit
    def _sdar_routed_tucker_mid_kernel(
        x_ptr,
        expert_ptr,
        u_exp_ptr,
        core_ptr,
        out_ptr,
        num_tokens: tl.constexpr,
        rank_in: tl.constexpr,
        rank_exp: tl.constexpr,
        rank_out: tl.constexpr,
        BLOCK_M: tl.constexpr,
        BLOCK_O: tl.constexpr,
        BLOCK_I: tl.constexpr,
    ):
        pid_m = tl.program_id(0)
        pid_o = tl.program_id(1)
        offs_m = pid_m * BLOCK_M + tl.arange(0, BLOCK_M)
        offs_o = pid_o * BLOCK_O + tl.arange(0, BLOCK_O)
        offs_i = tl.arange(0, BLOCK_I)

        experts = tl.load(expert_ptr + offs_m, mask=offs_m < num_tokens, other=0)
        acc = tl.zeros((BLOCK_M, BLOCK_O), dtype=tl.float32)

        for r in tl.range(0, rank_exp):
            expert_scale = tl.load(
                u_exp_ptr + experts * rank_exp + r,
                mask=offs_m < num_tokens,
                other=0.0,
            )
            for i0 in tl.range(0, rank_in, BLOCK_I):
                cur_i = i0 + offs_i
                x_vals = tl.load(
                    x_ptr + offs_m[:, None] * rank_in + cur_i[None, :],
                    mask=(offs_m[:, None] < num_tokens) & (cur_i[None, :] < rank_in),
                    other=0.0,
                )
                core_vals = tl.load(
                    core_ptr + r * rank_out * rank_in + offs_o[None, :] * rank_in + cur_i[:, None],
                    mask=(offs_o[None, :] < rank_out) & (cur_i[:, None] < rank_in),
                    other=0.0,
                )
                acc += expert_scale[:, None] * tl.dot(x_vals, core_vals)

        tl.store(
            out_ptr + offs_m[:, None] * rank_out + offs_o[None, :],
            acc,
            mask=(offs_m[:, None] < num_tokens) & (offs_o[None, :] < rank_out),
        )

    @triton.jit
    def _sdar_grouped_effective_tucker_mid_kernel(
        x_ptr,
        expert_offsets_ptr,
        effective_core_ptr,
        out_ptr,
        rank_in: tl.constexpr,
        rank_out: tl.constexpr,
        BLOCK_M: tl.constexpr,
        BLOCK_O: tl.constexpr,
        BLOCK_I: tl.constexpr,
    ):
        expert_id = tl.program_id(0)
        tile_m = tl.program_id(1)
        tile_o = tl.program_id(2)

        start = tl.load(expert_offsets_ptr + expert_id)
        end = tl.load(expert_offsets_ptr + expert_id + 1)
        offs_m = start + tile_m * BLOCK_M + tl.arange(0, BLOCK_M)
        offs_o = tile_o * BLOCK_O + tl.arange(0, BLOCK_O)
        offs_i = tl.arange(0, BLOCK_I)

        acc = tl.zeros((BLOCK_M, BLOCK_O), dtype=tl.float32)
        for i0 in tl.range(0, rank_in, BLOCK_I):
            cur_i = i0 + offs_i
            x_vals = tl.load(
                x_ptr + offs_m[:, None] * rank_in + cur_i[None, :],
                mask=(offs_m[:, None] < end) & (cur_i[None, :] < rank_in),
                other=0.0,
            )
            core_vals = tl.load(
                effective_core_ptr
                + expert_id * rank_out * rank_in
                + offs_o[None, :] * rank_in
                + cur_i[:, None],
                mask=(offs_o[None, :] < rank_out) & (cur_i[:, None] < rank_in),
                other=0.0,
            )
            acc += tl.dot(x_vals, core_vals)

        tl.store(
            out_ptr + offs_m[:, None] * rank_out + offs_o[None, :],
            acc,
            mask=(offs_m[:, None] < end) & (offs_o[None, :] < rank_out),
        )


def _sdar_triton_routed_tucker_mid(
    x_in: torch.Tensor,
    expert_indices: torch.Tensor,
    u_exp: torch.Tensor,
    core: torch.Tensor,
) -> Optional[torch.Tensor]:
    if not _sdar_tucker_triton_available or not x_in.is_cuda:
        return None
    if x_in.numel() == 0:
        return x_in.new_empty((0, core.shape[1]), dtype=torch.float32)

    x_in = x_in.contiguous()
    expert_indices = expert_indices.contiguous()
    u_exp = u_exp.contiguous()
    core = core.contiguous()

    num_tokens = x_in.shape[0]
    rank_exp, rank_out, rank_in = core.shape
    out = torch.empty(
        (num_tokens, rank_out),
        device=x_in.device,
        dtype=torch.float32,
    )

    block_m = 16
    block_o = 32
    block_i = 64
    grid = (triton.cdiv(num_tokens, block_m), triton.cdiv(rank_out, block_o))
    try:
        _sdar_routed_tucker_mid_kernel[grid](
            x_in,
            expert_indices,
            u_exp,
            core,
            out,
            num_tokens,
            rank_in,
            rank_exp,
            rank_out,
            BLOCK_M=block_m,
            BLOCK_O=block_o,
            BLOCK_I=block_i,
            num_warps=4,
        )
        return out
    except Exception:
        return None


def _sdar_triton_grouped_effective_tucker_mid(
    x_in: torch.Tensor,
    expert_offsets: torch.Tensor,
    effective_core: torch.Tensor,
) -> Optional[torch.Tensor]:
    if not _sdar_tucker_triton_available or not x_in.is_cuda:
        return None
    if x_in.numel() == 0:
        return x_in.new_empty((0, effective_core.shape[1]), dtype=torch.float32)

    x_in = x_in.contiguous()
    expert_offsets = expert_offsets.contiguous()
    effective_core = effective_core.contiguous()

    num_tokens = x_in.shape[0]
    num_experts, rank_out, rank_in = effective_core.shape
    counts = expert_offsets[1:] - expert_offsets[:-1]
    max_count = int(counts.max().item()) if counts.numel() > 0 else 0
    if max_count == 0:
        return x_in.new_zeros((num_tokens, rank_out), dtype=torch.float32)

    out = torch.empty((num_tokens, rank_out), device=x_in.device, dtype=torch.float32)
    block_m = 16
    block_o = 32
    block_i = 64
    grid = (
        num_experts,
        triton.cdiv(max_count, block_m),
        triton.cdiv(rank_out, block_o),
    )
    try:
        _sdar_grouped_effective_tucker_mid_kernel[grid](
            x_in,
            expert_offsets,
            effective_core,
            out,
            rank_in,
            rank_out,
            BLOCK_M=block_m,
            BLOCK_O=block_o,
            BLOCK_I=block_i,
            num_warps=4,
        )
        return out
    except Exception:
        return None


def _sdar_get_tucker_rank(config, role: str):
    ranks = getattr(config, "td_moe_ranks", None)
    if isinstance(ranks, dict) and role in ranks:
        return tuple(int(v) for v in ranks[role])
    raise ValueError(f"td_moe_ranks must define ranks for role '{role}'")


class SDARMoeTuckerLinear(nn.Module):
    def __init__(self, config, role: str, d_in: int, d_out: int):
        super().__init__()
        rank_exp, rank_out, rank_in = _sdar_get_tucker_rank(config, role)
        self.role = role
        self.d_in = d_in
        self.d_out = d_out
        self.rank_exp = rank_exp
        self.rank_out = rank_out
        self.rank_in = rank_in
        self.kernel = getattr(config, "td_moe_kernel", "triton")
        self.operator = getattr(config, "td_moe_operator", "effective")
        self.chunk_size = int(getattr(config, "td_moe_chunk_size", 2048))
        self.num_experts = config.num_experts

        self.core = nn.Parameter(torch.empty(rank_exp, rank_out, rank_in))
        self.u_exp = nn.Parameter(torch.empty(config.num_experts, rank_exp))
        self.u_out = nn.Parameter(torch.empty(d_out, rank_out))
        self.u_in = nn.Parameter(torch.empty(d_in, rank_in))
        self.register_buffer("effective_core", torch.empty(0), persistent=False)

    def _get_effective_core(self, dtype: torch.dtype) -> torch.Tensor:
        if (
            self.effective_core.numel() == 0
            or self.effective_core.device != self.core.device
            or self.effective_core.dtype != dtype
        ):
            with torch.no_grad():
                self.effective_core = torch.einsum(
                    "er,roi->eoi",
                    self.u_exp.to(dtype),
                    self.core.to(dtype),
                ).contiguous()
        return self.effective_core

    def _expert_offsets(self, expert_indices: torch.Tensor) -> torch.Tensor:
        boundaries = torch.arange(
            self.num_experts + 1,
            device=expert_indices.device,
            dtype=expert_indices.dtype,
        )
        return torch.searchsorted(expert_indices, boundaries).to(torch.int64)

    def _grouped_effective_mid_torch(
        self,
        x_in: torch.Tensor,
        expert_offsets: torch.Tensor,
        effective_core: torch.Tensor,
    ) -> torch.Tensor:
        mid = torch.empty(
            (x_in.shape[0], self.rank_out),
            device=x_in.device,
            dtype=x_in.dtype,
        )
        counts = expert_offsets[1:] - expert_offsets[:-1]
        active_experts = torch.nonzero(counts > 0, as_tuple=False).flatten()
        for expert_tensor in active_experts:
            expert_idx = int(expert_tensor.item())
            start = int(expert_offsets[expert_idx].item())
            end = int(expert_offsets[expert_idx + 1].item())
            mid[start:end] = torch.matmul(
                x_in[start:end],
                effective_core[expert_idx].transpose(0, 1),
            )
        return mid

    def _forward_chunk(self, x: torch.Tensor, expert_indices: torch.Tensor) -> torch.Tensor:
        x_dtype = x.dtype
        weight_dtype = self.u_in.dtype
        x_work = x.to(weight_dtype)
        x_in = torch.matmul(x_work, self.u_in)

        mid = None
        if self.operator == "effective":
            expert_offsets = self._expert_offsets(expert_indices)
            effective_core = self._get_effective_core(weight_dtype)
            if self.kernel == "triton":
                mid = _sdar_triton_grouped_effective_tucker_mid(
                    x_in,
                    expert_offsets,
                    effective_core,
                )
            if mid is None:
                mid = self._grouped_effective_mid_torch(
                    x_in,
                    expert_offsets,
                    effective_core,
                )

        if mid is None:
            core = self.core.to(weight_dtype)
            if self.kernel == "triton":
                mid = _sdar_triton_routed_tucker_mid(
                    x_in,
                    expert_indices,
                    self.u_exp.to(weight_dtype),
                    core,
                )
            if mid is None:
                core_perm = core.permute(0, 2, 1).contiguous()
                expanded_x = x_in.unsqueeze(0).expand(self.rank_exp, -1, -1)
                projected = torch.bmm(expanded_x, core_perm)
                u_exp_selected = self.u_exp[expert_indices].to(projected.dtype)
                mid = (projected * u_exp_selected.T.unsqueeze(2)).sum(dim=0)

        out = torch.matmul(mid.to(weight_dtype), self.u_out.to(weight_dtype).T)
        return out.to(x_dtype)

    def forward(self, x: torch.Tensor, expert_indices: torch.Tensor) -> torch.Tensor:
        if x.shape[0] <= self.chunk_size:
            return self._forward_chunk(x, expert_indices)

        outputs = []
        for start in range(0, x.shape[0], self.chunk_size):
            end = min(start + self.chunk_size, x.shape[0])
            outputs.append(self._forward_chunk(x[start:end], expert_indices[start:end]))
        return torch.cat(outputs, dim=0)


class SDARMoeTuckerGateUp(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.gate_proj = SDARMoeTuckerLinear(
            config,
            role="gate",
            d_in=config.hidden_size,
            d_out=config.moe_intermediate_size,
        )
        self.up_proj = SDARMoeTuckerLinear(
            config,
            role="up",
            d_in=config.hidden_size,
            d_out=config.moe_intermediate_size,
        )

    def forward(self, x: torch.Tensor, expert_indices: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        return self.gate_proj(x, expert_indices), self.up_proj(x, expert_indices)


class SDARMoeSparseMoeBlock(nn.Module):
    def __init__(self, config, layer_idx: Optional[int] = None):
        super().__init__()
        self.layer_idx = layer_idx
        self.num_experts = config.num_experts
        self.top_k = config.num_experts_per_tok
        self.norm_topk_prob = config.norm_topk_prob
        self.td_moe_enabled = bool(getattr(config, "td_moe_enabled", False))

        # gating
        self.gate = nn.Linear(config.hidden_size, config.num_experts, bias=False)
        if self.td_moe_enabled:
            self.act_fn = ACT2FN[config.hidden_act]
            self.gate_up_proj = SDARMoeTuckerGateUp(config)
            self.down_proj = SDARMoeTuckerLinear(
                config,
                role="down",
                d_in=config.moe_intermediate_size,
                d_out=config.hidden_size,
            )
        else:
            self.experts = nn.ModuleList(
                [
                    SDARMoeMLP(config, intermediate_size=config.moe_intermediate_size)
                    for _ in range(self.num_experts)
                ]
            )

    def _dispatch_to_experts(
        self,
        token_hidden_states: torch.Tensor,
        selected_experts: torch.Tensor,
        routing_weights: torch.Tensor,
    ) -> torch.Tensor:
        """
        Dispatch tokens to selected experts.

        Args:
            token_hidden_states: [num_tokens, hidden_dim]
            selected_experts:    [num_tokens, top_k]
            routing_weights:     [num_tokens, top_k]

        Returns:
            output_hidden_states: [num_tokens, hidden_dim]
        """
        num_tokens, hidden_dim = token_hidden_states.shape
        output_hidden_states = torch.zeros(
            (num_tokens, hidden_dim),
            dtype=token_hidden_states.dtype,
            device=token_hidden_states.device,
        )

        # Only visit experts that are actually selected.
        # This avoids scanning every expert when the active expert set is small.
        active_experts = torch.unique(selected_experts)
        # ITCMOE_RUNTIME_PROFILE: actual unique experts
        itcmoe_profile_add_activated_experts(active_experts.numel())


        for expert_idx_tensor in active_experts:
            expert_idx = int(expert_idx_tensor.item())
            token_pos, topk_pos = torch.where(selected_experts == expert_idx)

            if token_pos.numel() == 0:
                continue

            expert_layer = self.experts[expert_idx]
            current_state = token_hidden_states[token_pos]
            current_weight = routing_weights[token_pos, topk_pos, None]

            current_hidden_states = expert_layer(current_state) * current_weight
            output_hidden_states.index_add_(
                0,
                token_pos,
                current_hidden_states.to(token_hidden_states.dtype),
            )

        return output_hidden_states

    def _dispatch_to_tucker_experts(
        self,
        token_hidden_states: torch.Tensor,
        selected_experts: torch.Tensor,
        routing_weights: torch.Tensor,
    ) -> torch.Tensor:
        # ITCMOE_RUNTIME_PROFILE: final routed experts
        itcmoe_profile_add_activated_experts(
            torch.unique(selected_experts).numel()
        )
        num_tokens, hidden_dim = token_hidden_states.shape
        flat_experts = selected_experts.reshape(-1)
        flat_weights = routing_weights.reshape(-1)
        flat_token_pos = (
            torch.arange(num_tokens, device=token_hidden_states.device)
            .unsqueeze(1)
            .expand(-1, selected_experts.shape[1])
            .reshape(-1)
        )

        sort_idx = torch.argsort(flat_experts)
        flat_experts = flat_experts[sort_idx]
        flat_weights = flat_weights[sort_idx]
        flat_token_pos = flat_token_pos[sort_idx]
        routed_states = token_hidden_states.index_select(0, flat_token_pos)

        gate_states, up_states = self.gate_up_proj(routed_states, flat_experts)
        intermediate_states = self.act_fn(gate_states) * up_states
        routed_output = self.down_proj(intermediate_states, flat_experts)
        routed_output = routed_output * flat_weights[:, None]

        output_hidden_states = torch.zeros(
            (num_tokens, hidden_dim),
            dtype=token_hidden_states.dtype,
            device=token_hidden_states.device,
        )
        output_hidden_states.index_add_(0, flat_token_pos, routed_output.to(token_hidden_states.dtype))
        return output_hidden_states

    def forward(
        self,
        hidden_states: torch.Tensor,
        past_hidden_states=None,
        decoded_index=None,
        expert_limit_index=None,
    ) -> torch.Tensor:
        batch_size, sequence_length, hidden_dim = hidden_states.shape

        # ITCMOE_RUNTIME_PROFILE: one complete model forward
        if self.layer_idx == 0:
            itcmoe_profile_add_forward()

        # ============================================================
        # Case 1: no cached MoE output. Run the standard MoE path.
        # ============================================================
        if past_hidden_states is None:
            hidden_states_flat = hidden_states.view(-1, hidden_dim)

            # router_logits: [batch_size * sequence_length, num_experts]
            router_logits = self.gate(hidden_states_flat)

            routing_weights = F.softmax(
                router_logits,
                dim=1,
                dtype=torch.float,
            )

            routing_weights_topk, selected_experts = torch.topk(
                routing_weights,
                self.top_k,
                dim=-1,
            )

            if self.norm_topk_prob:
                routing_weights_topk = routing_weights_topk / routing_weights_topk.sum(
                    dim=-1,
                    keepdim=True,
                ).clamp_min(1e-12)

            routing_weights_topk = routing_weights_topk.to(hidden_states_flat.dtype)

            dispatch_fn = self._dispatch_to_tucker_experts if self.td_moe_enabled else self._dispatch_to_experts
            final_hidden_states = dispatch_fn(
                token_hidden_states=hidden_states_flat,
                selected_experts=selected_experts,
                routing_weights=routing_weights_topk,
            )

            final_hidden_states = final_hidden_states.reshape(
                batch_size,
                sequence_length,
                hidden_dim,
            )

            return final_hidden_states, router_logits

        # ============================================================
        # Case 2: cached MoE output exists.
        # decoded token: reuse past_hidden_states.
        # hot token: normal full router + top-k MoE.
        # cold token: use the mean hidden state of cold tokens to select
        #             a candidate expert set of size 3 * top_k, then each
        #             cold token re-selects top_k only inside that set.
        #
        # Here expert_limit_index=True is treated as cold_token=True.
        # ============================================================
        if decoded_index is None:
            decoded_index = torch.zeros(
                batch_size,
                sequence_length,
                dtype=torch.bool,
                device=hidden_states.device,
            )
        else:
            decoded_index = decoded_index.to(
                device=hidden_states.device,
                dtype=torch.bool,
            )

        if expert_limit_index is None:
            expert_limit_index = torch.zeros(
                batch_size,
                sequence_length,
                dtype=torch.bool,
                device=hidden_states.device,
            )
        else:
            expert_limit_index = expert_limit_index.to(
                device=hidden_states.device,
                dtype=torch.bool,
            )

        # True means this token still needs a MoE update.
        compute_mask = ~decoded_index

        hidden_states_flat = hidden_states.view(-1, hidden_dim)
        past_hidden_states_flat = past_hidden_states.view(-1, hidden_dim)
        compute_mask_flat = compute_mask.view(-1)
        expert_limit_index_flat = expert_limit_index.view(-1)

        # Keep the original output_router_logits interface.
        # Decoded tokens have zero router logits because they are not routed again.
        router_logits = torch.zeros(
            batch_size * sequence_length,
            self.num_experts,
            dtype=hidden_states.dtype,
            device=hidden_states.device,
        )

        # Use cached MoE output as the base. Only compute tokens overwrite it.
        final_hidden_states = past_hidden_states_flat.clone()

        if compute_mask_flat.any():
            compute_hidden_states = hidden_states_flat[compute_mask_flat]

            # Full router is computed once for all compute tokens.
            # Hot tokens directly use it.
            # Cold tokens use it again after masking by the centroid-selected pool.
            compute_router_logits = self.gate(compute_hidden_states)
            compute_routing_weights = F.softmax(
                compute_router_logits,
                dim=1,
                dtype=torch.float,
            )

            compute_routing_weights_topk, compute_selected_experts = torch.topk(
                compute_routing_weights,
                self.top_k,
                dim=-1,
            )

            # In the compute-token coordinate system, True means cold token.
            compute_cold_mask = expert_limit_index_flat[compute_mask_flat]

            if compute_cold_mask.any():
                cold_token_indices = torch.where(compute_cold_mask)[0]
                cold_hidden_states = compute_hidden_states[cold_token_indices]

                # Cold-token centroid: [1, hidden_dim]
                cold_mean_hidden = cold_hidden_states.mean(dim=0, keepdim=True)

                # Route the centroid and select 3 * top_k candidate experts.
                cold_centroid_router_logits = self.gate(cold_mean_hidden)
                cold_centroid_routing_weights = F.softmax(
                    cold_centroid_router_logits,
                    dim=-1,
                    dtype=torch.float,
                )

                cold_candidate_k = min(
                    self.num_experts,
                    max(self.top_k, 3 * self.top_k),
                )
                # print(cold_candidate_k)

                _, cold_candidate_experts = torch.topk(
                    cold_centroid_routing_weights,
                    cold_candidate_k,
                    dim=-1,
                )

                cold_candidate_mask = torch.zeros(
                    self.num_experts,
                    dtype=torch.bool,
                    device=hidden_states.device,
                )
                cold_candidate_mask[cold_candidate_experts.reshape(-1)] = True

                # For cold tokens, keep only the centroid-selected candidates.
                cold_routing_weights = compute_routing_weights[cold_token_indices].clone()
                cold_routing_weights[:, ~cold_candidate_mask] = 0

                cold_routing_weights_topk, cold_selected_experts = torch.topk(
                    cold_routing_weights,
                    self.top_k,
                    dim=-1,
                )

                compute_routing_weights_topk[cold_token_indices] = cold_routing_weights_topk
                compute_selected_experts[cold_token_indices] = cold_selected_experts

            if self.norm_topk_prob:
                compute_routing_weights_topk = compute_routing_weights_topk / compute_routing_weights_topk.sum(
                    dim=-1,
                    keepdim=True,
                ).clamp_min(1e-12)

            compute_routing_weights_topk = compute_routing_weights_topk.to(
                compute_hidden_states.dtype,
            )

            dispatch_fn = self._dispatch_to_tucker_experts if self.td_moe_enabled else self._dispatch_to_experts
            compute_final_hidden = dispatch_fn(
                token_hidden_states=compute_hidden_states,
                selected_experts=compute_selected_experts,
                routing_weights=compute_routing_weights_topk,
            )

            final_hidden_states[compute_mask_flat] = compute_final_hidden
            router_logits[compute_mask_flat] = compute_router_logits.to(router_logits.dtype)

        final_hidden_states = final_hidden_states.reshape(
            batch_size,
            sequence_length,
            hidden_dim,
        )

        return final_hidden_states, router_logits

@use_kernel_forward_from_hub("RMSNorm")
class SDARMoeRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        SDARMoeRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        return flash_rms_norm(
            hidden_states, weight=self.weight, bias=None, eps=self.variance_epsilon)
        '''
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * \
            torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)
        '''

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class SDARMoeDecoderLayer(nn.Module):
    def __init__(self, config: SDARMoeConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size

        self.self_attn = SDARMoeAttention(config, layer_idx)

        if (layer_idx not in config.mlp_only_layers) and (
            config.num_experts > 0 and (
                layer_idx + 1) % config.decoder_sparse_step == 0
        ):
            self.mlp = SDARMoeSparseMoeBlock(config, layer_idx=layer_idx)
        else:
            self.mlp = SDARMoeMLP(
                config, intermediate_size=config.intermediate_size)

        self.input_layernorm = SDARMoeRMSNorm(
            config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = SDARMoeRMSNorm(
            config.hidden_size, eps=config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_value: Optional[Tuple[torch.Tensor]] = None,
        output_attentions: Optional[bool] = False,
        output_router_logits: Optional[bool] = False,
        use_cache: Optional[bool] = False,
        store_kv: Optional[bool] = False,
        past_hidden_states = None,
        decoded_index = None,
        expert_limit_index = None,
        choice_id = None,
        new_hidden_states = None,
        cache_position: Optional[torch.LongTensor] = None,
        # necessary, but kept here for BC
        position_embeddings: Optional[Tuple[torch.Tensor,
                                            torch.Tensor]] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> Tuple[torch.FloatTensor, Optional[Tuple[torch.FloatTensor, torch.FloatTensor]]]:
        """
        Args:
            hidden_states (`torch.FloatTensor`): input to the layer of shape `(batch, seq_len, embed_dim)`
            attention_mask (`torch.FloatTensor`, *optional*): attention mask of size
                `(batch, sequence_length)` where padding elements are indicated by 0.
            output_attentions (`bool`, *optional*):
                Whether or not to return the attentions tensors of all attention layers. See `attentions` under
                returned tensors for more detail.
            output_router_logits (`bool`, *optional*):
                Whether or not to return the logits of all the routers. They are useful for computing the router loss,
                and should not be returned during inference.
            use_cache (`bool`, *optional*):
                If set to `True`, `past_key_values` key value states are returned and can be used to speed up decoding
                (see `past_key_values`).
            past_key_value (`Tuple(torch.FloatTensor)`, *optional*): cached past key and value projection states
            cache_position (`torch.LongTensor` of shape `(sequence_length)`, *optional*):
                Indices depicting the position of the input sequence tokens in the sequence.
            position_embeddings (`Tuple[torch.FloatTensor, torch.FloatTensor]`, *optional*):
                Tuple containing the cosine and sine positional embeddings of shape `(batch_size, seq_len, head_dim)`,
                with `head_dim` being the embedding dimension of each attention head.
            kwargs (`dict`, *optional*):
                Arbitrary kwargs to be ignored, used for FSDP and other methods that injects code
                into the model
        """

        residual = hidden_states

        hidden_states = self.input_layernorm(hidden_states)

        # Self Attention
        hidden_states, self_attn_weights = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_value=past_key_value,
            output_attentions=output_attentions,
            use_cache=use_cache,
            store_kv=store_kv,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
        )
        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)

        if past_hidden_states is not None:
            
            start_idx = choice_id * 32
            end_idx = start_idx + 32
            selected_hidden_states = past_hidden_states[:, start_idx:end_idx, :]
            
            past_hidden_states = torch.tile(selected_hidden_states, (1, 4, 1))
            hidden_states = self.mlp(hidden_states, past_hidden_states, decoded_index, expert_limit_index)
        else:
            hidden_states = self.mlp(hidden_states)
        
        if isinstance(hidden_states, tuple):
            hidden_states, router_logits = hidden_states
        else:
            router_logits = None

        new_hidden_states.append(hidden_states)
        hidden_states = residual + hidden_states

        outputs = (hidden_states,)

        if output_attentions:
            outputs += (self_attn_weights,)

        if output_router_logits:
            outputs += (router_logits,)

        return outputs


class SDARMoeRotaryEmbedding(nn.Module):
    def __init__(self, config: SDARMoeConfig, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and config.rope_scaling is not None:
            self.rope_type = config.rope_scaling.get(
                "rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(
            self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    # power user: used with advanced RoPE types (e.g. dynamic rope)
    @dynamic_rope_update
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(
            position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(
            x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @
                     position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


@auto_docstring
class SDARMoePreTrainedModel(PreTrainedModel):
    config_class = SDARMoeConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["SDARMoeDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn_2 = True
    _supports_sdpa = True
    _supports_flex_attn = True
    _supports_cache_class = True
    _supports_quantized_cache = True
    # MoE models don't work with torch.compile (`torch.where(condition)` not supported)
    _supports_static_cache = False
    _supports_attention_backend = True

    def _init_weights(self, module):
        std = self.config.initializer_range
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, nn.Embedding):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.padding_idx is not None:
                module.weight.data[module.padding_idx].zero_()
        elif isinstance(module, SDARMoeRMSNorm):
            module.weight.data.fill_(1.0)


@auto_docstring
class SDARMoeModel(SDARMoePreTrainedModel):
    def __init__(self, config: SDARMoeConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(
            config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [SDARMoeDecoderLayer(config, layer_idx)
             for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = SDARMoeRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = SDARMoeRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.embed_tokens

    def set_input_embeddings(self, value):
        self.embed_tokens = value

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[List[torch.FloatTensor]] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        store_kv: Optional[bool] = None,
        stored_hidden_states = None,
        decoded_index = None,
        expert_limit_index = None,
        choice_id = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        output_router_logits: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **flash_attn_kwargs: Unpack[FlashAttentionKwargs],
    ) -> MoeModelOutputWithPast:
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_router_logits = (
            output_router_logits if output_router_logits is not None else self.config.output_router_logits
        )
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        use_cache = use_cache if use_cache is not None else self.config.use_cache

        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError(
                "You must specify exactly one of input_ids or inputs_embeds")

        if self.gradient_checkpointing and self.training:
            if use_cache:
                logger.warning_once(
                    "`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`..."
                )
                use_cache = False

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache()

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length(
            ) if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )
        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        # causal_mask = self._update_causal_mask(
        #     attention_mask, inputs_embeds, cache_position, past_key_values, output_attentions
        # )

        hidden_states = inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        # decoder layers
        all_hidden_states = () if output_hidden_states else None
        all_self_attns = () if output_attentions else None
        all_router_logits = () if output_router_logits else None

        new_hidden_states = []
        past_hidden_states = None

        for idx, decoder_layer in enumerate(self.layers):
            if stored_hidden_states is not None:
                past_hidden_states = stored_hidden_states[idx]

            if output_hidden_states:
                all_hidden_states += (hidden_states,)

            if self.gradient_checkpointing and self.training:
                layer_outputs = self._gradient_checkpointing_func(
                    partial(decoder_layer.__call__, **flash_attn_kwargs),
                    hidden_states,
                    causal_mask,
                    position_ids,
                    past_key_values,
                    output_attentions,
                    output_router_logits,
                    use_cache,
                    cache_position,
                    position_embeddings,
                )
            else:
                layer_outputs = decoder_layer(
                    hidden_states,
                    attention_mask=attention_mask,
                    position_ids=position_ids,
                    past_key_value=past_key_values,
                    output_attentions=output_attentions,
                    output_router_logits=output_router_logits,
                    use_cache=use_cache,
                    store_kv=store_kv,
                    past_hidden_states = past_hidden_states,
                    decoded_index = decoded_index,
                    expert_limit_index = expert_limit_index,
                    choice_id = choice_id,
                    new_hidden_states = new_hidden_states,
                    cache_position=cache_position,
                    position_embeddings=position_embeddings,
                    **flash_attn_kwargs,
                )

            hidden_states = layer_outputs[0]
            # current_hidden_states.append(hidden_states) 

            if output_attentions:
                all_self_attns += (layer_outputs[1],)

            if output_router_logits:
                all_router_logits += (layer_outputs[-1],)

        hidden_states = self.norm(hidden_states)

        # add hidden states from the last decoder layer
        if output_hidden_states:
            all_hidden_states += (hidden_states,)

        return MoeModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values,
            hidden_states=all_hidden_states,
            attentions=all_self_attns,
            router_logits=all_router_logits,
        ), new_hidden_states

    def _update_causal_mask(
        self,
        attention_mask: Union[torch.Tensor, "BlockMask"],
        input_tensor: torch.Tensor,
        cache_position: torch.Tensor,
        past_key_values: Cache,
        output_attentions: bool = False,
    ):
        if self.config._attn_implementation == "flash_attention_2":
            if attention_mask is not None and past_key_values is not None:
                is_padding_right = attention_mask[:, -
                                                  1].sum().item() != input_tensor.size()[0]
                if is_padding_right:
                    raise ValueError(
                        "You are attempting to perform batched generation with padding_side='right'"
                        " this may lead to unexpected behaviour for Flash Attention version of SDARMoe. Make sure to "
                        " call `tokenizer.padding_side  = 'left'` before tokenizing the input. "
                    )
            if attention_mask is not None and 0.0 in attention_mask:
                return attention_mask
            return None
        if self.config._attn_implementation == "flex_attention":
            if isinstance(attention_mask, torch.Tensor):
                attention_mask = make_flex_block_causal_mask(attention_mask)
            return attention_mask

        # For SDPA, when possible, we will rely on its `is_causal` argument instead of its `attn_mask` argument, in
        # order to dispatch on Flash Attention 2. This feature is not compatible with static cache, as SDPA will fail
        # to infer the attention mask.
        past_seen_tokens = past_key_values.get_seq_length(
        ) if past_key_values is not None else 0
        using_static_cache = isinstance(past_key_values, StaticCache)
        using_sliding_window_cache = isinstance(
            past_key_values, SlidingWindowCache)

        # When output attentions is True, sdpa implementation's forward method calls the eager implementation's forward
        if (
            self.config._attn_implementation == "sdpa"
            and not (using_static_cache or using_sliding_window_cache)
            and not output_attentions
        ):
            if AttentionMaskConverter._ignore_causal_mask_sdpa(
                attention_mask,
                inputs_embeds=input_tensor,
                past_key_values_length=past_seen_tokens,
                sliding_window=self.config.sliding_window,
                is_training=self.training,
            ):
                return None

        dtype = input_tensor.dtype
        min_dtype = torch.finfo(dtype).min
        sequence_length = input_tensor.shape[1]
        # SlidingWindowCache or StaticCache
        if using_sliding_window_cache or using_static_cache:
            target_length = past_key_values.get_max_cache_shape()
        # DynamicCache or no cache
        else:
            target_length = (
                attention_mask.shape[-1]
                if isinstance(attention_mask, torch.Tensor)
                else past_seen_tokens + sequence_length + 1
            )

        # In case the provided `attention` mask is 2D, we generate a causal mask here (4D).
        causal_mask = self._prepare_4d_causal_attention_mask_with_cache_position(
            attention_mask,
            sequence_length=sequence_length,
            target_length=target_length,
            dtype=dtype,
            cache_position=cache_position,
            batch_size=input_tensor.shape[0],
            config=self.config,
            past_key_values=past_key_values,
        )

        if (
            self.config._attn_implementation == "sdpa"
            and attention_mask is not None
            and attention_mask.device.type in ["cuda", "xpu", "npu"]
            and not output_attentions
        ):
            # Attend to all tokens in fully masked rows in the causal_mask, for example the relevant first rows when
            # using left padding. This is required by F.scaled_dot_product_attention memory-efficient attention path.
            # Details: https://github.com/pytorch/pytorch/issues/110213
            causal_mask = AttentionMaskConverter._unmask_unattended(
                causal_mask, min_dtype)

        return causal_mask

    @staticmethod
    def _prepare_4d_causal_attention_mask_with_cache_position(
        attention_mask: torch.Tensor,
        sequence_length: int,
        target_length: int,
        dtype: torch.dtype,
        cache_position: torch.Tensor,
        batch_size: int,
        config: SDARMoeConfig,
        past_key_values: Cache,
    ):
        """
        Creates a causal 4D mask of shape `(batch_size, 1, query_length, key_value_length)` from a 2D mask of shape
        `(batch_size, key_value_length)`, or if the input `attention_mask` is already 4D, do nothing.

        Args:
            attention_mask (`torch.Tensor`):
                A 2D attention mask of shape `(batch_size, key_value_length)` or a 4D attention mask of shape `(batch_size, 1, query_length, key_value_length)`.
            sequence_length (`int`):
                The sequence length being processed.
            target_length (`int`):
                The target length: when generating with static cache, the mask should be as long as the static cache, to account for the 0 padding, the part of the cache that is not filled yet.
            dtype (`torch.dtype`):
                The dtype to use for the 4D attention mask.
            cache_position (`torch.Tensor`):
                Indices depicting the position of the input sequence tokens in the sequence.
            batch_size (`torch.Tensor`):
                Batch size.
            config (`SDARMoeConfig`):
                The model's configuration class
            past_key_values (`Cache`):
                The cache class that is being used currently to generate
        """
        if attention_mask is not None and attention_mask.dim() == 4:
            # In this case we assume that the mask comes already in inverted form and requires no inversion or slicing.
            causal_mask = attention_mask
        else:
            min_dtype = torch.finfo(dtype).min
            causal_mask = torch.full(
                (sequence_length, target_length), fill_value=min_dtype, dtype=dtype, device=cache_position.device
            )
            diagonal_attend_mask = torch.arange(target_length, device=cache_position.device) > cache_position.reshape(
                -1, 1
            )
            text_config = config.get_text_config()
            if getattr(text_config, "use_sliding_window", True) and text_config.sliding_window is not None:
                # if we have sliding window, we should not attend to tokens beyond sliding window length, so we mask them out also
                # the check is needed to verify is current checkpoint was trained with sliding window or not
                if not isinstance(past_key_values, SlidingWindowCache) or sequence_length > target_length:
                    sliding_attend_mask = torch.arange(target_length, device=cache_position.device) <= (
                        cache_position.reshape(-1, 1) -
                        text_config.sliding_window
                    )
                    diagonal_attend_mask.bitwise_or_(sliding_attend_mask)
            causal_mask *= diagonal_attend_mask
            causal_mask = causal_mask[None, None,
                                      :, :].expand(batch_size, 1, -1, -1)
            if attention_mask is not None:
                causal_mask = causal_mask.clone()  # copy to contiguous memory for in-place edit
                if attention_mask.shape[-1] > target_length:
                    attention_mask = attention_mask[:, :target_length]
                mask_length = attention_mask.shape[-1]
                padding_mask = causal_mask[:, :, :, :mask_length] + attention_mask[:, None, None, :].to(
                    causal_mask.device
                )
                padding_mask = padding_mask == 0
                causal_mask[:, :, :, :mask_length] = causal_mask[:, :, :, :mask_length].masked_fill(
                    padding_mask, min_dtype
                )
        return causal_mask


class KwargsForCausalLM(FlashAttentionKwargs, LossKwargs):
    ...


def load_balancing_loss_func(
    gate_logits: Union[torch.Tensor, Tuple[torch.Tensor], None],
    num_experts: Optional[int] = None,
    top_k=2,
    attention_mask: Optional[torch.Tensor] = None,
) -> Union[torch.Tensor, int]:
    r"""
    Computes auxiliary load balancing loss as in Switch Transformer - implemented in Pytorch.

    See Switch Transformer (https://arxiv.org/abs/2101.03961) for more details. This function implements the loss
    function presented in equations (4) - (6) of the paper. It aims at penalizing cases where the routing between
    experts is too unbalanced.

    Args:
        gate_logits:
            Logits from the `gate`, should be a tuple of model.config.num_hidden_layers tensors of
            shape [batch_size X sequence_length, num_experts].
        num_experts:
            Number of experts
        top_k:
            The number of experts to route per-token, can be also interpreted as the `top-k` routing
            parameter.
        attention_mask (`torch.Tensor`, *optional*):
            The attention_mask used in forward function
            shape [batch_size X sequence_length] if not None.

    Returns:
        The auxiliary loss.
    """
    if gate_logits is None or not isinstance(gate_logits, tuple):
        return 0

    if isinstance(gate_logits, tuple):
        compute_device = gate_logits[0].device
        concatenated_gate_logits = torch.cat(
            [layer_gate.to(compute_device) for layer_gate in gate_logits], dim=0)

    routing_weights = torch.nn.functional.softmax(
        concatenated_gate_logits, dim=-1)

    _, selected_experts = torch.topk(routing_weights, top_k, dim=-1)

    expert_mask = torch.nn.functional.one_hot(selected_experts, num_experts)

    if attention_mask is None:
        # Compute the percentage of tokens routed to each experts
        tokens_per_expert = torch.mean(expert_mask.float(), dim=0)

        # Compute the average probability of routing to these experts
        router_prob_per_expert = torch.mean(routing_weights, dim=0)
    else:
        batch_size, sequence_length = attention_mask.shape
        num_hidden_layers = concatenated_gate_logits.shape[0] // (
            batch_size * sequence_length)

        # Compute the mask that masks all padding tokens as 0 with the same shape of expert_mask
        expert_attention_mask = (
            attention_mask[None, :, :, None, None]
            .expand((num_hidden_layers, batch_size, sequence_length, top_k, num_experts))
            .reshape(-1, top_k, num_experts)
            .to(compute_device)
        )

        # Compute the percentage of tokens routed to each experts
        tokens_per_expert = torch.sum(expert_mask.float() * expert_attention_mask, dim=0) / torch.sum(
            expert_attention_mask, dim=0
        )

        # Compute the mask that masks all padding tokens as 0 with the same shape of tokens_per_expert
        router_per_expert_attention_mask = (
            attention_mask[None, :, :, None]
            .expand((num_hidden_layers, batch_size, sequence_length, num_experts))
            .reshape(-1, num_experts)
            .to(compute_device)
        )

        # Compute the average probability of routing to these experts
        router_prob_per_expert = torch.sum(routing_weights * router_per_expert_attention_mask, dim=0) / torch.sum(
            router_per_expert_attention_mask, dim=0
        )

    overall_loss = torch.sum(
        tokens_per_expert * router_prob_per_expert.unsqueeze(0))
    return overall_loss * num_experts


@auto_docstring
class SDARMoeForCausalLM(SDARMoePreTrainedModel, GenerationMixin):
    _tied_weights_keys = ["lm_head.weight"]
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = SDARMoeModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(
            config.hidden_size, config.vocab_size, bias=False)
        self.router_aux_loss_coef = config.router_aux_loss_coef
        self.num_experts = config.num_experts
        self.num_experts_per_tok = config.num_experts_per_tok

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.model.embed_tokens

    def set_input_embeddings(self, value):
        self.model.embed_tokens = value

    def get_output_embeddings(self):
        return self.lm_head

    def set_output_embeddings(self, new_embeddings):
        self.lm_head = new_embeddings

    def set_decoder(self, decoder):
        self.model = decoder

    def get_decoder(self):
        return self.model

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[List[torch.FloatTensor]] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        stored_hidden_states = None,
        decoded_index = None,
        expert_limit_index = None,
        choice_id = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        output_router_logits: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[KwargsForCausalLM],
    ) -> MoeCausalLMOutputWithPast:
        r"""
        labels (`torch.LongTensor` of shape `(batch_size, sequence_length)`, *optional*):
            Labels for computing the masked language modeling loss. Indices should either be in `[0, ...,
            config.vocab_size]` or -100 (see `input_ids` docstring). Tokens with indices set to `-100` are ignored
            (masked), the loss is only computed for the tokens with labels in `[0, ..., config.vocab_size]`.

        Example:

        ```python
        >>> from transformers import AutoTokenizer, SDARForCausalLM

        >>> model = SDARForCausalLM.from_pretrained("DiffuOpen/SDAR-1.7B-Chat")
        >>> tokenizer = AutoTokenizer.from_pretrained("DiffuOpen/SDAR-1.7B-Chat")

        >>> prompt = "Hey, are you conscious? Can you talk to me?"
        >>> inputs = tokenizer(prompt, return_tensors="pt")

        >>> # Generate
        >>> generate_ids = model.generate(inputs.input_ids, max_length=30)
        >>> tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        "Hey, are you conscious? Can you talk to me?\nI'm not conscious, but I can talk to you."
        ```"""

        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_router_logits = (
            output_router_logits if output_router_logits is not None else self.config.output_router_logits
        )

        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )

        # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
        outputs, new_hidden_states = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            stored_hidden_states = stored_hidden_states,
            decoded_index = decoded_index,
            expert_limit_index = expert_limit_index,
            choice_id = choice_id,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            output_router_logits=output_router_logits,
            cache_position=cache_position,
            **kwargs,
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep,
                              None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        loss = None
        if labels is not None:
            loss = self.loss_function(
                logits, labels, self.vocab_size, **kwargs)

        aux_loss = None
        if output_router_logits:
            aux_loss = load_balancing_loss_func(
                outputs.router_logits,
                self.num_experts,
                self.num_experts_per_tok,
                attention_mask,
            )
            if labels is not None:
                # make sure to reside in the same device
                loss += self.router_aux_loss_coef * aux_loss.to(loss.device)

        return MoeCausalLMOutputWithPast(
            loss=loss,
            aux_loss=aux_loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            router_logits=outputs.router_logits,
        ), new_hidden_states


__all__ = [
    "SDARMoeForCausalLM",
    "SDARMoeModel",
    "SDARMoePreTrainedModel",
]
